disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - type_name
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
