language: objective-c
osx_image: xcode10

script:
  - xcodebuild test -project HowToSolveByComputer/How To Solve It By Computer/How To Solve It By Computer.xcodeproj -scheme How To Solve It By Computer -destination "platform=iOS Simulator,name=iPhone 7" -sdk iphonesimulator11.0 CODE_SIGNING_REQUIRED=NO
  
